### ISSUE TITLE
Valor total da compra ao final do registro

### ISSUE THREAD

**Issue by Evilim** [Evilim/Projeto-LP-III#1]
Nessa funcionalidade, é necessário implementar quatro métodos, um para calcular o valor unitário de cada item baseado nas características do produto, um para calcular o frete respeitando os critérios para cada categoria e suas dimensões, um para calcular o valor de frete total, e por fim, um método para somar o valor total do frete com o valor total dos produtos contidos no carrinho.

**Comment by mathiasbrito** [comment]
Onde esses métodos devem ser implementados? em quais classes? Quando você descreve o Issue é importante apontar para esses detalhes caso as classes já existam. Tudo que vc descreveu parece meio solto, pois não posso entender em qual classe eles estariam encapsulados.

**Comment by mathiasbrito** [comment]
Tou vendo que você fechou o Issue e reabriu, se certifique de que ao fechar vc indicará os comits que implementam essa funcionalidade.

**Comment by Evilim** [comment]
Issue implementado no commit a seguir:

f35b0b845a094cc395acceeeba1c12d218a957d7

public void finalCompra(ModeloCarrinho carrinho){
        System.out.printf("\nValor total da compra: %.2f",carrinho.getValor());
        System.out.println("\nCompra efetuada com sucesso, agradecemos a preferencia!\n");
    }
