### ISSUE TITLE
Como usuário eu gostaria de ter mais detalhes do sistema na documentação (README.md)

### ISSUE THREAD

**Issue by mathiasbrito** [Evilim/Projeto-LP-III#5]
O README.md atual apenas lista detalhes de implementação, é necessário que ele explique do que se trata o programa, qual seu objetivo e como ele funciona. Em breve ele deve descreve como instalar e usar o sistema. Se certifique de corrigir isso.

**Comment by Evilim** [comment]
Issue implementado no commit a seguir:

192735a234326f973d106caca5de3392870abd0a
