### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Evilim** [Evilim/Projeto-LP-III#7]
Como usuário, gostaria de ter um acesso particular ao meus dados na loja e aos produtos o qual desejo comprar.

**Comment by mathiasbrito** [comment]
tenta ser um pouco mias específica no título, um processo de Login possui vários aspectos o que deseja implementar? Se esse issue for uma discussão, ou um levantamento do que se precisa implementar para ter um Login, ele ira se desdobrar em vários issues que vc deve referenciar nesse aqui. Então este termina quando os desdobramentos forem implementados. Mas o título precisa ser um pouco mais específico. "Análise do sistema de login do sistema", por exemplo. Caso seja implementação "Implementação do sistema de login do sistema".

**Comment by Evilim** [comment]
Issue implementado no commit a seguir:

f35b0b845a094cc395acceeeba1c12d218a957d7

```java
public ModeloCliente loginCliente(){
        System.out.println("\nNome de Usuario: ");
        String nome=leitor.nextLine();
        System.out.println("Senha: ");
        String senha=leitor.nextLine();
        ModeloCliente cliente=new ModeloCliente(nome, senha);
        return cliente;
    }
